/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as MeRouteImport } from './routes/me'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSongsRouteImport } from './routes/admin.songs'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ArtistIdRouteImport } from './routes/artist.$id'
import { Route as SongIdRouteImport } from './routes/song.$id'
import { Route as SongIdEditRouteImport } from './routes/song.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSongsRoute = AdminSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ArtistIdRoute = ArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SongIdRoute = SongIdRouteImport.update({
  id: '/song/$id',
  path: '/song/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SongIdEditRoute = SongIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SongIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/songs': typeof AdminSongsRoute
  '/admin/users': typeof AdminUsersRoute
  '/artist/$id': typeof ArtistIdRoute
  '/song/$id': typeof SongIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/song/$id/edit': typeof SongIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/songs': typeof AdminSongsRoute
  '/admin/users': typeof AdminUsersRoute
  '/artist/$id': typeof ArtistIdRoute
  '/song/$id': typeof SongIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/song/$id/edit': typeof SongIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/songs': typeof AdminSongsRoute
  '/admin/users': typeof AdminUsersRoute
  '/artist/$id': typeof ArtistIdRoute
  '/song/$id': typeof SongIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/song/$id/edit': typeof SongIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/library'
    | '/me'
    | '/notifications'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/upload'
    | '/admin/comments'
    | '/admin/content'
    | '/admin/reports'
    | '/admin/songs'
    | '/admin/users'
    | '/artist/$id'
    | '/song/$id'
    | '/admin/'
    | '/song/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/library'
    | '/me'
    | '/notifications'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/upload'
    | '/admin/comments'
    | '/admin/content'
    | '/admin/reports'
    | '/admin/songs'
    | '/admin/users'
    | '/artist/$id'
    | '/song/$id'
    | '/admin'
    | '/song/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/library'
    | '/me'
    | '/notifications'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/upload'
    | '/admin/comments'
    | '/admin/content'
    | '/admin/reports'
    | '/admin/songs'
    | '/admin/users'
    | '/artist/$id'
    | '/song/$id'
    | '/admin/'
    | '/song/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  LibraryRoute: typeof LibraryRoute
  MeRoute: typeof MeRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UploadRoute: typeof UploadRoute
  ArtistIdRoute: typeof ArtistIdRoute
  SongIdRoute: typeof SongIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/songs': {
      id: '/admin/songs'
      path: '/songs'
      fullPath: '/admin/songs'
      preLoaderRoute: typeof AdminSongsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/artist/$id': {
      id: '/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof ArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song/$id': {
      id: '/song/$id'
      path: '/song/$id'
      fullPath: '/song/$id'
      preLoaderRoute: typeof SongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song/$id/edit': {
      id: '/song/$id/edit'
      path: '/edit'
      fullPath: '/song/$id/edit'
      preLoaderRoute: typeof SongIdEditRouteImport
      parentRoute: typeof SongIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSongsRoute: typeof AdminSongsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCommentsRoute: AdminCommentsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSongsRoute: AdminSongsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SongIdRouteChildren {
  SongIdEditRoute: typeof SongIdEditRoute
}

const SongIdRouteChildren: SongIdRouteChildren = {
  SongIdEditRoute: SongIdEditRoute,
}

const SongIdRouteWithChildren =
  SongIdRoute._addFileChildren(SongIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  LibraryRoute: LibraryRoute,
  MeRoute: MeRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UploadRoute: UploadRoute,
  ArtistIdRoute: ArtistIdRoute,
  SongIdRoute: SongIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
